name: SOAT | FIAP | CI/CD Completo - Qualidade e Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY_NAME: order
  EKS_CLUSTER_NAME: soat-challenge-eks-cluster

jobs:
  quality_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Instalar dependências
        run: npm ci

      - name: Validar Build (Compilação)
        run: npm run build

      - name: Rodar testes com cobertura
        run: npm run test:cov
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: admin
          DB_PASSWORD: password
          DB_NAME: order_db_test
          PORT: 3000
          SQS_ORDER_CREATED_URL: https://sqs.us-east-1.amazonaws.com/000/order-created
          SQS_PRODUCTION_STARTED_URL: https://sqs.us-east-1.amazonaws.com/000/production-started
          SQS_PRODUCTION_READY_URL: https://sqs.us-east-1.amazonaws.com/000/production-ready
          SQS_PRODUCTION_COMPLETED_URL: https://sqs.fake/production-withdrawn
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: fake
          AWS_SECRET_ACCESS_KEY: fake

  build_and_deploy:
    needs: quality_check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar as credenciais da AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Fazer login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push to ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Configurar o kubeconfig para o cluster EKS
        run: aws eks --region ${{ env.AWS_REGION }} update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Implantação no EKS
        run: |
          IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY_NAME }}:${{ github.sha }}

          # Atualiza o deployment 'order-deployment' no container 'order'
          kubectl set image deployment/order-deployment order-container="$IMAGE_URI"

          kubectl rollout status deployment/order-deployment --timeout=120s
